"""

Revision ID: 58fd5407108e
Revises: 386616c098b0
Create Date: 2020-12-14 10:41:56.177403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fd5407108e'
down_revision = '386616c098b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###